### ISSUE TITLE
Timeouts seems not work in DistributedLock.Redis

### ISSUE THREAD

**Issue by ccccccmd** [madelson/DistributedLock#148] opened 2022-11-07 17:13 UTC
> there is no -1 return after 5 seconds but after almost 30 seconds.

```C#
  await using var handle =await _lockProvider.TryAcquireLockAsync("MyLockName", TimeSpan.FromSeconds(5));
  if (handle != null)
  {    
      await Task.Delay(TimeSpan.FromSeconds(500));
      return 1;
  }
  else
  {
      return -1;
  }

```

**Comment by madelson** [comment] 2022-11-08 01:20
@ccccccmd thanks for filing. I'm not able to reproduce this behavior; when I run this code snippet it times out after 5s as expected.

Can you please provide a minimal repro that reproduces the behavior?

**Comment by ccccccmd** [comment] 2022-11-08 02:51
> @ccccccmd thanks for filing. I'm not able to reproduce this behavior; when I run this code snippet it times out after 5s as expected.
> 
> Can you please provide a minimal repro that reproduces the behavior?

Thanks for quick reply.

It happened during the second visit to the API.

https://github.com/ccccccmd/WebApplication1

**Comment by madelson** [comment] 2022-11-08 12:32
Hi @ccccccmd thanks for putting this together. I downloaded your app and ran your repo. The only change I made was changing the redis connection string to `"localhost:6379"` to hit my local redis (I'm running 4.0.9 64-bit in WSL).

I first opened one tab, which spun for a long time (made sense because of the 500s wait).

Then I opened another tab and it spun for a bit before printing:
![image](https://user-images.githubusercontent.com/1269046/200559584-c9ffd0d3-d36f-4463-aca8-af91e179f07c.png)

Refreshing produced the same thing. **Oddly, though, while the printed time always shows ~5000ms, the wall-clock time for the request is substantially longer; ~20s**.

I tried setting a breakpoint at the start of the `MapGet` block; and indeed there is a 10-15s delay before each request even enters that block... weird.

Then I ripped out the DistributedLock code and replaced with a simple `SemaphoreSlim`: same behavior.

Then I tried running the app _not_ in debug mode (CTRL+F5) and the problem goes away.

I've reported this to ASP.NET Core here: https://github.com/dotnet/aspnetcore/issues/44940.

**Can you try my repro steps and see if you get the same behavior I do?**

**Comment by ccccccmd** [comment] 2022-11-08 12:50
Many thanks [madelson](https://github.com/madelson)!

I get the same behavior as you describe in release mode.

It's weird ☺.

**Comment by madelson** [comment] 2022-11-09 01:00
Appreciate the confirmation @ccccccmd . I'm closing this issue for now since it doesn't appear to be specific to this library. It will be interesting to see what MSFT says.

**Closed by madelson** 2022-11-09 01:00 UTC
